deploy

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -15,8 +15,8 @@ jobs:
       - name: Checkout Source
         uses: actions/checkout@v4
 
-      - name: Login to docker hub
-        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+      - name: Login to Docker Hub
+        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
       - name: Build Docker Image
         run: docker build -t zunsod/proshop-backend .
@@ -32,9 +32,20 @@ jobs:
         run: docker pull zunsod/proshop-backend:latest
 
       - name: Stop and remove existing container
+        # Use || true to prevent the workflow from failing if the container doesn't exist
         run: |
           docker stop proshop-backend-container || true
           docker rm proshop-backend-container || true
 
-      - name: Run docker container
-        run: docker run -d -p 5000:5000 --name proshop-backend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' zunsod/proshop-backend:latest
+      - name: Run docker container with environment variables
+        run: |
+          docker run -d \
+          -p 5000:5000 \
+          --name proshop-backend-container \
+          -e PORT=${{ secrets.PORT }} \
+          -e MONGO_URL=${{ secrets.MONGO_URL }} \
+          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
+          -e PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }} \
+          -e CORS_ORIGINS=${{ secrets.CORS_ORIGINS }} \
+          -e PAGINATION_LIMIT=${{ secrets.PAGINATION_LIMIT }} \
+          zunsod/proshop-backend:latest
